#============================================================================
#
# simple project makefile (main.cpp + one other file)
#
# (c) Wouter van Ooijen (wouter@voti.nl) 2017-2020
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
#============================================================================

# source files in this project (main.* is automatically assumed)
# SOURCES += second.cpp

# header files in this project
HEADERS +=

# other places to look for files for this project
SEARCH  +=

# other things to build (for instance main.lss)
RESULTS +=

# set RELATIVE to the next higher directory
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/makefile.link
