################################################################################
#
# makefile
#
################################################################################
#
# makefile that creates the reference documentation
#
################################################################################
#
# (c) Wouter van Ooijen (www.voti.nl) 2020
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
################################################################################

.PHONY: reference

reference:
	python make_reference.py
